/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-01-23 09:24:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Ozip_005fwrite_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	if(session.getAttribute("loginEmail")==null) {

      out.write("\r\n");
      out.write("		<script>alert(\"로그인해주십시오\"); location.href=\"Controller?command=login_form\";</script>\r\n");

	} 

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>오집in 질문 글쓰기 | 라이프스타일 슈퍼앱, 오늘의집</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"../css/All.css\">\r\n");
      out.write("	<!-- <link rel=\"stylesheet\" href=\"css/header.css\"> -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/Mypage_shopping.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/Ozip_write_page.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" as=\"style\" crossorigin href=\"https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css\" />\r\n");
      out.write("	<script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		//메뉴 밑줄\r\n");
      out.write("		$(function(){\r\n");
      out.write("			$(\".active\").click(function(){\r\n");
      out.write("				$(this).addClass('on');\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"Controller?command=Ozip_write\" method=\"post\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div class=\"fixed-container\" style=\"height: 81px;\">\r\n");
      out.write("			<div id = \"header\">\r\n");
      out.write("				<div id = \"header_inner\">\r\n");
      out.write("				<div class = \"test\">\r\n");
      out.write("					<div class=\"logo\"><a href=\"#\"><img src=\"images/logo.png\"/></a></div>\r\n");
      out.write("					<div class=\"topSelect\">\r\n");
      out.write("						<div class=\"top_icon\">\r\n");
      out.write("							<div class=\"top_icon3\">\r\n");
      out.write("								<button type=\"submit\" id=\"jy_upload\">\r\n");
      out.write("									<div><span>올리기</span></div>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"clear:both;\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>			\r\n");
      out.write("		<div style=\"clear:both\"></div>\r\n");
      out.write("	</header>\r\n");
      out.write("		<div class=\"page_all\">\r\n");
      out.write("			<div class=\"write_content_tl\"><!-- 사진 , 글 content 들어감 -->\r\n");
      out.write("				<div class=\"asdfg\">\r\n");
      out.write("					<div class=\"input_img_area\">\r\n");
      out.write("						<div class=\"input_img_area_flex\">\r\n");
      out.write("							<span class=\"camera_i_con\"></span>\r\n");
      out.write("							<span class=\"img_minfo_i_con\">사진을 끌어다 놓으세요</span>\r\n");
      out.write("							<span class=\"img_sinfo_i_con\">10장까지 올릴 수 있어요.</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button class=\"img_bring_here\">PC에서 불러오기</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"content_content_content\">\r\n");
      out.write("						<input type=\"text\" name=\"OzipTitle\" class=\"write_ozip_title\" maxlength=\"30\" placeholder=\"제목을 입력해주세요.\"/>\r\n");
      out.write("						<!-- <div class=\"write_ozip\" name=\"OzipDescription\" spellcheck=\"false\" contenteditable=\"true\" placeholder=\"어떤 질문인지 짧은 소개로 시작해보세요.&#10;다양한 태그도 사용 가능해요!\"></div> -->\r\n");
      out.write("						<textarea class=\"write_ozip\" name=\"OzipDescription\" placeholder=\"어떤 질문인지 짧은 소개로 시작해보세요.&#10;다양한 태그도 사용 가능해요!\"></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<button  type=\"button\" class=\"jy_tag_btn\">\r\n");
      out.write("						클릭하여 주요 키워드를 입력해주세요.\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
